seo:
  title: Vambie
  description: Join our community of creators and bring Vambies to life to show you are worthy of your own, unique Vambie.

discord_invite_link: https://discord.gg/ZhMGDB5tUV

dmca_policy_link: https://storage.googleapis.com/tyk-static/Taiyaki%20-%20Website%20Copyright%20(DMCA)%20Policy%204146-7059-1039%201.pdf
